### PR TITLE
Dependencies update and missing babel plugins

### PR DESCRIPTION
**Pull request by casimiro**
I cloned the repo and tried to run the example but I had problem with old dependencies.
I updated all dependencies and added the babel plugins that were listed in .babelrc but not in package.json. With this changes I was able to run the example.

### CODE REVIEW

**Comment by casimiro** [comment]
Maybe it would be a good idea to check if all these babel plugins are really necessary. I am new to this front world so I can't tell that easily.

**Comment by cristiandley** [comment]
hey @casimiro , i had none issue compiling the package, you got some errors doing it ? no extra plugin are required if you have babel-cli.

try to check that out :)

**Comment by skipjack** [comment]
I think now the best practice is to use `babel-preset-env` which will automagically determine which stages/presets are necessary.

**Comment by jeremiahrhall** [comment]
@casimiro Is this still an issue?

**Comment by casimiro** [comment]
@jeremiahrhall not anymore. sorry not closing it earlier.

**Pull request closed without merging**
