### PR TITLE
Support layers as in react-leaflet 1.0.0

### LINKED ISSUE #3: this.props.map undefined if HeatMap component is nested inside LayersControl
The heat map renders fine if the component is directly inside the react-leaflet <Map> component, e.g.:

```
<Map center={[52.629729, -1.131592]} zoom={6}>
      <HeatmapLayer
            points={this.props.points}
            longitudeExtractor={m => m['location'][0]}
            latitudeExtractor={m => m['location'][1]}
            gradient={gradient}
            intensityExtractor={m => m['weight']}
      />
</Map>
```

However, if it is nested inside the react-leaflet <LayersControl> component (see example below), get an error 'Uncaught TypeError: Cannot read property 'getSize' of undefined'. It seems like this.props.map is not passed down to react-leaflet-heatmap-layer <HeatmapLayer> component in this case.

```
<Map center={[52.629729, -1.131592]} zoom={6}>
   <LayersControl position="topright">
       <Overlay>
           <HeatmapLayer
                points={this.props.points}
                longitudeExtractor={m => m['location'][0]}
                latitudeExtractor={m => m['location'][1]}
                gradient={gradient}
                intensityExtractor={m => m['weight']}
            />
       </Overlay>
  </LayersControl>
</Map>
```

These are the file imports for reference:

```

import React, {PropTypes} from 'react';
import { Map, TileLayer, Marker, LayersControl} from 'react-leaflet';
const { BaseLayer, Overlay } = LayersControl;
import { divIcon, point } from 'leaflet';
import HeatmapLayer from 'react-leaflet-heatmap-layer';
```

### PR DESCRIPTION
**Pull request by MartinSahlen**
This pull request fixes #3 that @ruta-goomba addressed. Now, the heatmap can live inside nested controls as well as outside. It will respect toggling layers on and off.

### CODE REVIEW

**Comment by MartinSahlen** [comment]
This repo seems to have a lot in common with this: https://github.com/Leaflet/Leaflet.heat. I would strongly suggest just using this layer instead of duplicating a lot of functionality. Now (and with my pull request) this codebase is somewhat of a hybrid between a leaflet plugin and a react component.

**Comment by evansiroky** [comment]
@jeremiahrhall any chance you can merge this in?

**Comment by jeremiahrhall** [comment]
Hi @MartinSahlen and @evansiroky I will make sure to review this tomorrow.

**Comment by evansiroky** [comment]
Awesome!  I found an issue with the unmounting/removing of the layer and am working on a PR to @MartinSahlen's branch.

**Comment by evansiroky** [comment]
See https://github.com/MartinSahlen/react-leaflet-heatmap-layer/pull/1

**Comment by MartinSahlen** [comment]
So it seems you added linting to master @jeremiahrhall, so there seems to be some more changes needed to get this in because of conflicts. Have applied all the requested changes, maybe @evansiroky wants to have a shot at the conflicts?

**Comment by evansiroky** [comment]
Can do.  I'm out of town for the weekend, so I'll take care of this on Monday or Tuesday.

**Comment by evansiroky** [comment]
@MartinSahlen, see https://github.com/MartinSahlen/react-leaflet-heatmap-layer/pull/2

**Comment by MartinSahlen** [comment]
@evansiroky Great!

**Comment by MartinSahlen** [comment]
@jeremiahrhall Are you able to get this in?

**Comment by skipjack** [comment]
This also fixes #13, correct? Would love to see this merged... loving react-leaflet so far but the api change is somewhat blocking our migration. Will use @MartinSahlen's fork for the time being.

**Comment by MartinSahlen** [comment]
@jeremiahrhall are you able to get this in? Seems like quite a few people are eagerly awaiting this :D

**Comment by jeremiahrhall** [comment]
Hello folks. My apologies for the long delay in getting this merged in. Thanks @MartinSahlen and @evansiroky for putting this together and seeing this through!

**Comment by MartinSahlen** [comment]
Wohoo :D

**Pull request merged**
